//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternationalSOS_api.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Patient_Id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
        public int Doctor_Id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
